# Does the random-walk BSSRDF conserve energy against the albedo it is given?
#
# Motivation: the pbrt head renders noticeably darker and redder with the
# subsurface BSDF than with Disney, on the same albedo map and the same light.
# That could be physics (a dielectric boundary really does darken a scattering
# medium) or a bug in our inversion. This isolates it.
#
# Setup: a convex sphere alone under a constant radiance-1 environment. There is
# no other geometry, so no interreflection: a Lambertian sphere of albedo A must
# render exactly A in every pixel, whatever the shading normal does. Rendering
# the same sphere with <bsdf type="subsurface"> at the same albedo therefore
# reads the achieved reflectance straight off the film, and the ratio to A is
# the energy the walk loses.
#
# usage: python _sss_furnace.py [--spp 256]
import os, sys, math, subprocess, importlib.util
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "scenes", "_sss_furnace")
EXE = os.path.join(HERE, "build", "Release", "nori-dxr.exe")
SPP = int(sys.argv[sys.argv.index('--spp') + 1]) if '--spp' in sys.argv else 256
W, H = 200, 200

_s = importlib.util.spec_from_file_location('exrtool', os.path.join(HERE, '_exrtool.py'))
exrtool = importlib.util.module_from_spec(_s)
_argv, sys.argv = sys.argv, [sys.argv[0]]
_s.loader.exec_module(exrtool)
sys.argv = _argv

# Unit sphere at the origin, built here rather than reused from cbox so the
# radius is exactly 1 and "radius / sphere diameter" is easy to read.
def write_sphere(path, rings=128, segs=256):
    with open(path, 'w') as o:
        o.write("# unit sphere, generated by _sss_furnace.py\n")
        for i in range(rings + 1):
            th = math.pi * i / rings
            for j in range(segs):
                ph = 2 * math.pi * j / segs
                x = math.sin(th) * math.cos(ph)
                y = math.cos(th)
                z = math.sin(th) * math.sin(ph)
                o.write('v %.6f %.6f %.6f\n' % (x, y, z))
        for i in range(rings + 1):
            th = math.pi * i / rings
            for j in range(segs):
                ph = 2 * math.pi * j / segs
                o.write('vn %.6f %.6f %.6f\n' % (math.sin(th) * math.cos(ph),
                                                 math.cos(th),
                                                 math.sin(th) * math.sin(ph)))
        for i in range(rings):
            for j in range(segs):
                a = i * segs + j + 1
                b = i * segs + (j + 1) % segs + 1
                c = (i + 1) * segs + j + 1
                d = (i + 1) * segs + (j + 1) % segs + 1
                o.write('f %d//%d %d//%d %d//%d\n' % (a, a, c, c, d, d))
                o.write('f %d//%d %d//%d %d//%d\n' % (a, a, d, d, b, b))


SCENE = """<?xml version='1.0' encoding='utf-8'?>
<!-- white furnace: constant radiance 1 in every direction, one convex sphere,
     nothing else. A Lambertian sphere of albedo A renders exactly A. -->
<scene>
\t<string name="envmap" value="white.hdr"/>
\t<float name="envmapScale" value="1.0"/>
\t<float name="evCompensation" value="0.0"/>
\t<camera type="perspective">
\t\t<float name="fov" value="40"/>
\t\t<transform name="toWorld">
\t\t\t<lookat target="0,0,0" origin="0,0,4" up="0,1,0"/>
\t\t</transform>
\t\t<integer name="width" value="%d"/>
\t\t<integer name="height" value="%d"/>
\t</camera>
\t<sampler type="independent"><integer name="sampleCount" value="%d"/></sampler>
\t<mesh type="obj">
\t\t<string name="filename" value="sphere.obj"/>
%s
\t</mesh>
</scene>
"""

DIFFUSE = """\t\t<bsdf type="diffuse">
\t\t\t<color name="albedo" value="%.6f %.6f %.6f"/>
\t\t</bsdf>"""

WALK = """\t\t<bsdf type="subsurface">
\t\t\t<color name="albedo" value="%.6f %.6f %.6f"/>
\t\t\t<float name="radius"    value="%.6g"/>
\t\t\t<float name="intIOR"    value="%.4f"/>
\t\t\t<float name="extIOR"    value="1.0"/>
\t\t\t<float name="g"         value="0.0"/>
\t\t\t<float name="roughness" value="0.2962"/>
\t\t\t<float name="specular"  value="0.0"/>
\t\t</bsdf>"""


def write_white_hdr(path, value=1.0):
    e = 136 + math.floor(math.log2(value / 255.0)) + 1
    b = int(round(value / 2.0 ** (e - 136)))
    while b > 255:
        e += 1
        b = int(round(value / 2.0 ** (e - 136)))
    open(path, 'wb').write(b"#?RADIANCE\nFORMAT=32-bit_rle_rgbe\n\n-Y 4 +X 4\n"
                          + bytes([b, b, b, e]) * 16)


def render(name, bsdf):
    p = os.path.join(OUT, name + '.xml')
    open(p, 'w').write(SCENE % (W, H, SPP, bsdf))
    for f in os.listdir(OUT):
        if f.startswith('snapshot_'):
            os.remove(os.path.join(OUT, f))
    subprocess.run([EXE, name + '.xml', '--headless'], cwd=OUT,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    exr = os.path.join(OUT, 'snapshot_%d.exr' % SPP)
    img = exrtool.read(exr)
    if isinstance(img, tuple):
        img = img[0]
    img = np.asarray(img, np.float64)[..., :3]
    # sample a disc well inside the silhouette: the rim is grazing incidence,
    # where a dielectric boundary legitimately goes bright, and averaging it in
    # would flatter the walk. This measures the face-on reflectance.
    yy, xx = np.mgrid[0:img.shape[0], 0:img.shape[1]]
    cy, cx = img.shape[0] / 2.0, img.shape[1] / 2.0
    # the sphere fills 2 / (2 * 4 * tan(20 deg)) of the frame width
    rad_px = img.shape[1] * (1.0 / (2.0 * 4.0 * math.tan(math.radians(20.0))))
    m = ((yy - cy) ** 2 + (xx - cx) ** 2) < (0.6 * rad_px) ** 2
    return img[m].reshape(-1, 3).mean(0)


def main():
    os.makedirs(OUT, exist_ok=True)
    write_sphere(os.path.join(OUT, 'sphere.obj'))
    write_white_hdr(os.path.join(OUT, 'white.hdr'))

    # skin-ish per-channel albedo plus two neutrals, so a wavelength-dependent
    # loss shows up as a spread between the channels of the first row
    A = (0.55, 0.30, 0.22)
    print("white furnace, unit sphere, %d spp. A Lambertian sphere reads its "
          "own albedo.\n" % SPP)
    lam = render('diffuse', DIFFUSE % A)
    print("diffuse   A=%.2f %.2f %.2f            -> %.4f %.4f %.4f  (should be A)"
          % (A + tuple(lam)))
    print()
    print("%-38s %-24s %s" % ("subsurface", "measured", "fraction of A"))
    for ior in (1.0, 1.33):
        for r in (0.0023, 0.01, 0.05, 0.25, 1.0):
            v = render('walk_%s_%s' % (ior, r), WALK % (A + (r, ior)))
            f = np.array(v) / np.array(A)
            print("  intIOR %.2f  radius %-6.4g (mfp/diam %.4f)  %.4f %.4f %.4f   "
                  "%.3f %.3f %.3f" % (ior, r, r / 2.0, v[0], v[1], v[2],
                                      f[0], f[1], f[2]))
        print()


if __name__ == '__main__':
    main()
