#!/usr/bin/env python3
"""Generate a deliberately hard many-light Cornell box for the ReSTIR-DI A/B.

Design notes, because the obvious version of this scene is too easy:

  * 256 lights, but only 8 emitter *meshes*. Lights are grouped into radiance
    tiers, one mesh per tier, each holding 32 quads. The per-triangle emitter CDF
    already handles picking within a mesh, so this gets 256 lights for 8 BLAS
    instead of 256.
  * Tiers span a 128x radiance range and are spatially *interleaved*, not
    clustered. If the bright lights sat together, every shading point would see
    roughly one tier and power-weighted selection would have nothing to do.
  * Slat baffles hang below the ceiling. Without occlusion each point sees every
    light, single-sample NEE does fine, and RIS has nothing to win - which is
    exactly why the older cbox_manylight (64 equal, unoccluded ceiling lights)
    showed no benefit.
  * Diffuse only. The mirror/dielectric spheres in the standard cbox inject
    delta-path noise that direct-lighting resampling cannot touch, which would
    dilute the measurement.
"""
import io, math, os

REPO = os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))))  # tools/scene_build/ -> repo root
OUT = os.path.join(REPO, "scenes", "final_scenes", "cbox")
GRID = 16                 # 16x16 = 256 lights
TIERS = 8
Y_LIGHT = 1.575           # just below the y=1.59 ceiling
SPAN = 0.86               # half-extent of the light grid in x and z
HALF = 0.020              # light quad half-size (small -> hard visibility)

def quad(f, cx, cz, y, h, base):
    """Ceiling quad wound so the geometric normal points -y, matching light.obj."""
    for vx, vz in ((cx + h, cz - h), (cx + h, cz + h), (cx - h, cz + h), (cx - h, cz - h)):
        f.write(f"v {vx:.6f} {y:.6f} {vz:.6f}\n")
    f.write(f"f {base+0} {base+1} {base+2}\nf {base+3} {base+0} {base+2}\n")
    return base + 4

# --- emitter meshes, one per radiance tier -------------------------------------
counts = [0] * TIERS
files = [io.open(f"{OUT}/restir_lights_t{t}.obj", "w") for t in range(TIERS)]
bases = [1] * TIERS
for i in range(GRID):
    for j in range(GRID):
        # co-prime strides interleave the tiers so neighbouring lights differ
        t = (i * 5 + j * 3) % TIERS
        cx = -SPAN + 2 * SPAN * i / (GRID - 1)
        cz = -SPAN + 2 * SPAN * j / (GRID - 1)
        bases[t] = quad(files[t], cx, cz, Y_LIGHT, HALF, bases[t])
        counts[t] += 1
for f in files:
    f.close()

# --- baffles: vertical fins hanging from the ceiling ---------------------------
# Horizontal slats were nearly edge-on to the camera and barely blocked anything.
# Fins that hang *down* between the light rows are what make visibility vary from
# pixel to pixel: a floor point sees only the lights whose slot it can look up
# through. That per-pixel visibility variation is precisely what spatial reuse
# exploits, and what the old cbox_manylight scene completely lacked.
with io.open(f"{OUT}/restir_slats.obj", "w") as f:
    b = 1
    # Hang only ~0.15 below the lights. Full-length fins blanketed the ceiling
    # from the camera and wasted the top third of frame; short fins still block
    # grazing angles (so which lights a point can see depends on where it is)
    # while leaving steep angles open.
    NFIN, Y_TOP, Y_BOT = 12, 1.57, 1.42
    for k in range(NFIN):
        cz = -0.95 + 1.9 * k / (NFIN - 1)
        for vx, vy in ((1.0, Y_TOP), (1.0, Y_BOT), (-1.02, Y_BOT), (-1.02, Y_TOP)):
            f.write(f"v {vx:.6f} {vy:.6f} {cz:.6f}\n")
        f.write(f"f {b+0} {b+1} {b+2}\nf {b+3} {b+0} {b+2}\n")
        b += 4

# --- scene xml ------------------------------------------------------------------
# tier k is 2^k brighter than tier 0 -> 128x spread, so power-weighted selection
# and RIS both have real work to do
hues = [(1.00, 0.35, 0.30), (0.35, 1.00, 0.45), (0.40, 0.55, 1.00), (1.00, 0.85, 0.35),
        (0.95, 0.40, 0.95), (0.40, 0.95, 0.95), (1.00, 0.65, 0.30), (0.75, 0.75, 1.00)]
lights_xml = []
for t in range(TIERS):
    # tier 0 = 1.0, tier 7 = 128. Mean radiance across tiers works out near the
    # single-light cbox's, so the image lands at a comparable exposure while the
    # 128x spread still gives power-weighted selection real work.
    scale = 1.0 * (2.0 ** t)
    r, g, b = (c * scale for c in hues[t])
    lights_xml.append(
        f'''    <!-- tier {t}: {counts[t]} lights, radiance x{2**t} -->
    <mesh type="obj">
        <string name="filename" value="restir_lights_t{t}.obj"/>
        <emitter type="area"><color name="radiance" value="{r:.2f} {g:.2f} {b:.2f}"/></emitter>
    </mesh>''')

xml = f'''<?xml version='1.0' encoding='utf-8'?>
<!-- Hard many-light cbox for the ReSTIR-DI A/B (untracked, generated by
     tools/scene_build/make_restir_scene.py - edit that, not this).

     {GRID*GRID} lights in {TIERS} emitter meshes, radiance spanning {2**(TIERS-1)}x,
     spatially interleaved, behind slat baffles. Diffuse only: the usual
     mirror/dielectric spheres add delta-path noise that direct-lighting
     resampling cannot fix and would only dilute the measurement.

     A/B:  USE_RIS=0 vs USE_RIS=1  ->  means must match (unbiased), and the
           equal-spp direct-lighting noise is the win. -->
<scene>
    <camera type="perspective">
        <float name="fov" value="27.7856"/>
        <transform name="toWorld">
            <scale value="-1,1,1"/>
            <lookat target="0, 0.893051, 4.41198" origin="0, 0.919769, 5.41159" up="0, 1, 0"/>
        </transform>
        <integer name="height" value="600"/>
        <integer name="width" value="800"/>
    </camera>
    <sampler type="independent">
        <integer name="sampleCount" value="64"/>
    </sampler>

    <mesh type="obj">
        <string name="filename" value="meshes/walls.obj"/>
        <bsdf type="diffuse"><color name="albedo" value="0.725 0.71 0.68"/></bsdf>
    </mesh>
    <mesh type="obj">
        <string name="filename" value="meshes/rightwall.obj"/>
        <bsdf type="diffuse"><color name="albedo" value="0.161 0.133 0.427"/></bsdf>
    </mesh>
    <mesh type="obj">
        <string name="filename" value="meshes/leftwall.obj"/>
        <bsdf type="diffuse"><color name="albedo" value="0.630 0.065 0.05"/></bsdf>
    </mesh>

    <!-- diffuse occluders: hard shadows + interreflection, no delta paths -->
    <mesh type="obj">
        <string name="filename" value="meshes/sphere1.obj"/>
        <bsdf type="diffuse"><color name="albedo" value="0.65 0.65 0.65"/></bsdf>
    </mesh>
    <mesh type="obj">
        <string name="filename" value="meshes/sphere2.obj"/>
        <bsdf type="diffuse"><color name="albedo" value="0.55 0.58 0.52"/></bsdf>
    </mesh>
    <mesh type="obj">
        <string name="filename" value="restir_slats.obj"/>
        <bsdf type="diffuse"><color name="albedo" value="0.35 0.35 0.37"/></bsdf>
    </mesh>

{chr(10).join(lights_xml)}
</scene>
'''
io.open(f"{OUT}/cbox_restir.xml", "w").write(xml)
print(f"wrote {OUT}/cbox_restir.xml")
print(f"  {GRID*GRID} lights in {TIERS} meshes: {counts}")
print(f"  radiance spread {2**(TIERS-1)}x, 11 slat baffles, {GRID*GRID*2} light triangles")
